services:
  app:
    image: nginx:latest
    ports:
      - "8080:80"
    environment:
      - DEBUG=true
    volumes:
      - ./app:/var/www/html

  db:
    image: postgres
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root123
    networks:
      - host  
      
networks:
  host:  
    external: true