services:
  app:
    image: python:latest
    ports:
      - "5000:5000" 
    environment:
      - SECRET_KEY=1234
    networks:
      - host 

  db:
    image: postgres
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root123
    networks:
      - host  
      
networks:
  host:  
    external: true