version: '3.9'

services:
  app:
    image: nginx:1.27.1
    ports:
      - "127.0.0.1:8080:80"
    environment:
      - DEBUG=false
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    networks:
      - app_net

  db:
    image: postgres:14
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - db_net

networks:
  app_net:
    driver: bridge
  db_net:
    driver: bridge
