services:
  app:
    image: python:3.9-slim
    ports:
      - "127.0.0.1:8080:5000"  
    environment:
      SECRET_KEY: ${SECRET_KEY}  
    networks:
      - app_net  

  db:
    image: postgres:14
    ports:
      - "127.0.0.1:5433:5432" 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  
    networks:
      - app_net  

networks:
  app_net:  