name: Bad Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Python version
        run: python3 -m venv .venv
        continue-on-error: true

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          npm install 

      - name: Run tests
        run: python -m unittest discover tests

      - name: Deploy
        run: |
          scp -r dist/ user@server:/deploy_path  
          echo "SECRET_KEY=1234" >> $GITHUB_ENV  


 