name: Goodworkflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set env
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          
    - name: Build Docker image
      run: |
        docker build -t myapp1 .

    - name: Run npm install
      run: |
        docker run --rm my-app npm ci --ignore-scripts

    - name: Run tests
      run: |
        docker run --rm my-app npm test

    - name: Deploy
      run: rsync -avz --delete dist/ ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.DEPLOY_PATH }}
